// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2iJQJmgag2dModhPy1Ss_Gdt-dO1GYEQ',
    appId: '1:52507066764:web:5489e6e593f6cc442a96a9',
    messagingSenderId: '52507066764',
    projectId: 'accesories-store-flutterfb',
    authDomain: 'accesories-store-flutterfb.firebaseapp.com',
    storageBucket: 'accesories-store-flutterfb.firebasestorage.app',
    measurementId: 'G-BBKCX23H46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlL9feWNc0Q3xRfBAdQf8ft8Vv1fPVdaA',
    appId: '1:52507066764:android:f4c1d3195fdbc98a2a96a9',
    messagingSenderId: '52507066764',
    projectId: 'accesories-store-flutterfb',
    storageBucket: 'accesories-store-flutterfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHId46lGEbeKPMZCGPYLoih_VBvjjQmFE',
    appId: '1:52507066764:ios:d795526e79a86a832a96a9',
    messagingSenderId: '52507066764',
    projectId: 'accesories-store-flutterfb',
    storageBucket: 'accesories-store-flutterfb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHId46lGEbeKPMZCGPYLoih_VBvjjQmFE',
    appId: '1:52507066764:ios:d795526e79a86a832a96a9',
    messagingSenderId: '52507066764',
    projectId: 'accesories-store-flutterfb',
    storageBucket: 'accesories-store-flutterfb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2iJQJmgag2dModhPy1Ss_Gdt-dO1GYEQ',
    appId: '1:52507066764:web:1447fbf3be4f91dd2a96a9',
    messagingSenderId: '52507066764',
    projectId: 'accesories-store-flutterfb',
    authDomain: 'accesories-store-flutterfb.firebaseapp.com',
    storageBucket: 'accesories-store-flutterfb.firebasestorage.app',
    measurementId: 'G-X17ZHCPVZ1',
  );
}
